spring:
  application:
    name: task
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:memory:myDb?cache=shared
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
api:
  security:
    token:
      secret: jui2h97872ny627db72bd63nj8
server:
  port: 8080

logging:
  file:
    name: logs/app.log
    path: logs
    max-size: 10MB
  level:
    root: INFO
    org.springframework.web: DEBUG
    br.janioofi.task: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
